baseurl: /
highlighter: pygments
title: Typeblog
name: Typeblog
description: Typing....
url: https://typeblog.net
paginate: 5
disqus_shortname: hxbdx
paginate_path: "page:num"
markdown: redcarpet
style_version: 201511272138

redcarpet:
 extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
