baseurl: /
pygments: true
title: Typeblog
name: Typeblog
description: Typing....
url: https://typeblog.net
paginate: 5
disqus_shortname: hxbdx
paginate_path: "page:num"
markdown: rdiscount
style_version: 201503311658
